function imageProcess

panelColor=get(0,'DefaultUicontrolBackgroundColor');
log_c={'1'};
pow_c={'1','0.4'};
bound={'100'};

    function figResize(src,evt)
        fpos=get(f,'Position');
        set(upPanel,'Position',...
            [0,fpos(4)*2/3,fpos(3),fpos(4)*1/3]);
        set(centerPanel,'Position',...
            [0,fpos(4)*1/3,fpos(3),fpos(4)*1/3]);
        set(boPanel,'Position',...
            [0,0,fpos(3),fpos(4)*1/3]);
    end

    function readFileFcn(src,evt)
        [fname,dirpath]=uigetfile({'*.jpg';'*.jpeg';'*.bmp';'*.png'});
        file=[dirpath fname];
        set(readImage,'String',file);
    end
    function j=threshold_processing(i)
        b=str2num(cell2mat(bound(1)));
        if i<=b
            j=0;
        else
            j=255;
        end    
    end
    function showImageFcn(src,evt)
        file=get(readImage,'String');
        value=get(selectMenu,'Value');
        image=imread(file);
        switch value
            case 1
                figure('Name','原图');
                imshow(image);
            case 2
                figure('Name','图像反转');
                imshow( imadjust(image,[0,1],[1,0]));%第一个为输入范围，第二个为输出范围，而如果左边大于右边的，则实现灰度反转。不管范围是多少，始终是[0,1]
                %而如果图像是[0,255]，imadjust会乘以255来扩大范围。
            case 3
                figure('Name','对数变换');
                coe=str2num(cell2mat(log_c));%因为cell中的元素类型仍然是cell，所以先使用cell2mat将cell转换成数组，而对于单个元素的则是转换成该元素本身的类型
                g=im2uint8(mat2gray(coe*log(1+double(image))));%mat2gray将值限定在[0,1]范围，再使用im2uint8将值的范围变换成[0,255]。
                imshow(g);
            case 4
                figure('Name','幂次变换');
                coe1=str2num(cell2mat(pow_c(1)));
                coe2=str2num(cell2mat(pow_c(2)));
                g=im2uint8(mat2gray(coe1*double(image).^coe2));%之所以要用double就是因为整数的幂次只能是整数，所以为了进行非整数的乘方，需要使用double函数
                imshow(g);
            case 5
                figure('Name','阈值处理');
                g=arrayfun(@threshold_processing,image);
                imshow(g);
            case 6
                figure('Name','直方图均衡化');
                g=histeq(image,256);%256表示输出图像的灰度级，默认为64
                imshow(g);
        end
    end

    function upPanelResize(src,evt)
        bpos2=get(upPanel,'Position');
        set(readImage,'Position',...
            [0,0,bpos2(3)*5/12,bpos2(4)]);
        set(readFile,'Position',...
            [1+bpos2(3)*5/12,0,bpos2(3)*1/12,bpos2(4)]);
    end
    function boPanelResize(src,evt)
        bpos=get(boPanel,'Position');
        set(showImage,'Position',...
            [0,0,bpos(3)*1/12,bpos(4)]);
    end
    function centerPanelResize(src,evt)
         bpos1=get(centerPanel,'Position');
         set(Label1,'Position',...
             [0,0,bpos1(3)*1/12,bpos1(4)]);
         set (selectMenu,'Position',...
             [bpos1(3)*1/12+1,0,bpos1(3)*1/6,bpos1(4)]);
         set(setButton,'Position',...
             [bpos1(3)*1/4+2,0,bpos1(3)*1/12,bpos1(4)]);
         set(showButton,'Position',...
             [bpos1(3)*1/3+3,0,bpos1(3)*1/6,bpos1(4)]);
    end
%获取所选中的值，使用string属性得到总共有哪些值，然后使用value得到所选中的是哪一个即可
    function setFcn(src,evt)
        str=get(selectMenu,'String');
        value=get(selectMenu,'Value');
        
        switch value
            case {1,2,6}
                msgbox('灰度变换,原图和均衡化处理不需要设置参数','提示','none');
            case 3
                log_c=inputdlg('输入对数变换的常数系数','对数变换参数设置',1,{'1'});
            case 4
                pow_c=inputdlg({'常数设置','指数设置'},'幂次变换参数设置',1,{'1','1'});
            case 5
                bound=inputdlg('输入阈值','阈值处理阈值设置',1,{'100'});
        end
    end
    function showHist(src,evt)
        file=get(readImage,'String');
        image=imread(file);
        figure('Name','直方图显示');
        imhist(image,25); %这里25表示将[0,255]共256个值等分为25份，所以显示的直方图只有25个横坐标值
    end

f=figure('Units','characters',...
    'Position',[10 10 120 9],...
    'Color',panelColor,...
    'HandleVisibility','callback',...
    'Renderer','painters',...
    'Name','read&save image',...
    'Toolbar','figure',...
    'ResizeFcn',@figResize);

%对比upPanel和centerPanel可以知道，如果该控件里面包含多个子控件，则需要定义Resize函数

upPanel=uipanel('BackgroundColor',panelColor,...
    'Units','characters',...
    'Position',[0,6,120,3],...
    'Parent',f,...
    'ResizeFcn',@upPanelResize);

readImage=uicontrol(f,'Style','edit','Units','characters',...
    'Position',[0 0 50 3],...
    'BackgroundColor','white',...
    'String','E:\数字图像处理\4366441_000657169359_2.jpg',...
    'Parent',upPanel,'Max',2);
readFile=uicontrol(f,'Style','pushbutton','Units','characters',...
    'Position',[51,0,10,3],...
    'BackgroundColor','white',...
    'String','选择图片',...
    'Parent',upPanel,...
    'Callback',@readFileFcn);


centerPanel=uipanel('BackgroundColor',panelColor,...
    'Units','characters',...
    'Position',[0,3,120,3],...
    'Parent',f,...
    'ResizeFcn',@centerPanelResize);
Label1=uicontrol(f,'Style','text','Units','characters',...
    'Position',[0,0,10,3],...
    'String','增强方法选择',...
    'Parent',centerPanel,...
    'BackgroundColor',panelColor);

%String中的数组是单元数组，因为如果没有加上{}使成为单元数组，则每一个字符串的一个字符就是该行的
%一列，而数组要求每一个维度的长度是一样的，所以没有加上{}的话要求每一个字符串的字数是一样的
selectMenu=uicontrol(f,'Style','popupmenu','Units','characters',...
    'Position',[11,0,20,3],...
    'Parent',centerPanel,...
    'String',[{'原图'};{'图像反转'};{'对数变换'};{'幂次变换'};{'阈值处理'};{'直方图处理'}],...
    'BackgroundColor','white');
setButton=uicontrol(f,'Style','pushbutton','Units','characters',...
    'Position',[32,0,10,3],...
    'Parent',centerPanel,...
    'String','参数设置',...
    'BackgroundColor',panelColor,...
    'Callback',@setFcn);
showButton=uicontrol(f,'Style','pushbutton','Units','characters',...
    'Position',[43,0,20,3],...
    'Parent',centerPanel,...
    'String','直方图显示',...
    'BackgroundColor',panelColor,...
    'Callback',@showHist);

boPanel=uipanel('BackgroundColor',panelColor,...
    'Units','characters',...
    'Position',[0,0,120,3],...
    'Parent',f,...
    'ResizeFcn',@boPanelResize);
showImage=uicontrol(f,'Style','pushbutton','Units','characters',...
    'Position',[0,0,10,3],...
    'BackgroundColor','white',...
    'String','显示图片',...
    'Parent',boPanel,...
    'Callback',@showImageFcn);
end